name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.amelchebil }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        run: |
          docker build -t task-manager .
          docker tag task-manager ${{ secrets.amelchebil }}/task-manager:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/task-manager:latest